<?php

namespace school\UserBundle\Repository;

/**
 * FatherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FatherRepository extends \Doctrine\ORM\EntityRepository
{
}
